In [1]:
import numpy as np

## חיבור מטריצות

### אוטומטי:

In [9]:
A = [[4,  1,  7], [2,  8,  3], [5,  9,  0]]

B = [[2,  6,  1], [7,  0,  5] ,[3,  4,  9]]

In [15]:
A = np.array(A)
B = np.array(B)

In [29]:
result = A+B

In [31]:
print(result)

[[ 6  7  8]
 [ 9  8  8]
 [ 8 13  9]]


### ידני:

In [ ]:
A = [4  1  7] 
    [2  8  3]
    [5  9  0]

B = [2  6  1]
    [7  0  5]
    [3  4  9]

In [ ]:
A + B = 
            4+2 = 6
            1+6 = 7
            7+1 = 8

            2+7 = 9
            8+0 = 8
            3+5 = 8

            5+3 = 8
            9+4 = 13
            0+9 = 9


In [ ]:
A + B = [6  7  8]
        [9  8  8]
        [8 13  9]

# חיסור מטריצות

### אוטומטי:

In [25]:
C = [[8 , 2], [5,  7], [3,  9]]
D = [[1 , 4], [6,  2],[0,  5]]

In [27]:
C = np.array(C)
D = np.array(D)

In [37]:
result = C-D

In [39]:
print(result)

[[ 7 -2]
 [-1  5]
 [ 3  4]]


### ידני:

In [ ]:
C = [8  2]
    [5  7]
    [3  9]

D = [1  4]
    [6  2]
    [0  5]

In [ ]:
C - D = 
            8-1 = 7
            2-4 = -2

            5-6 = -1
            7-2 = 5

            3-0 = 3
            9-5 = 4
            

In [ ]:
C - D =   [7 -2]
          [-1 5]
          [3  4]

# כפל מטריצות

### אוטומטי:

In [57]:
E = [[2,  0,  3,  1], [4,  5,  2,  7], [1,  3, 6,  2]]
F = [[3,  1,  2], [0,  4,  6], [7,  2,  5], [1,  8,  3]]

In [59]:
E = np.array(E)
F = np.array(F)

In [63]:
result = E @ F

In [65]:
print(result)

[[28 16 22]
 [33 84 69]
 [47 41 56]]


### ידני:

In [ ]:
E = [2  0  3  1]
    [4  5  2  7]
    [1  3  6  2]

F = [3  1  2]
    [0  4  6]
    [7  2  5]
    [1  8  3]

In [ ]:
E * F = 
            2*3 = 6  + 
            0*0 = 0  +
            3*7 = 21 +
            1*1 = 1  =    28

            2*1 = 2  +
            0*4 = 0  +
            3*2 = 6  +
            1*8 = 8  =    16

            2*2 = 4  +
            0*6 = 0  +
            3*5 = 15 +
            1*3 = 3  =    22



            4*3 = 12 +
            5*0 = 0  +
            2*7 = 14 +
            7*1 = 7  =    33

            4*1 = 4  +
            5*4 = 20 +
            2*2 = 4  +
            7*8 = 56 =    84

            4*2 = 8  +
            5*6 = 30 +
            2*5 = 10 +
            7*3 = 21  =   69



            1*3 = 3  +
            3*0 = 0  +
            6*7 = 42 +
            2*1 = 2  =    47

            1*1 = 1  +
            3*4 = 12 +
            6*2 = 12 +
            2*8 = 16 =    41

            1*2 = 2  +
            3*6 = 18 +
            6*5 = 30 +
            2*3 = 6  =    56
            
            

            

In [ ]:
E * F =   [28 16 22]
          [33 84 69]
          [47 41 56]

# טרנספוזיציה של מטריצה

### אוטומטי:

In [82]:
G = [[5,  2,  8,  4], [1,  7,  3,  9], [6,  0,  5,  2], [3,  8,  1,  7]]

In [84]:
G = np.array(G)

In [86]:
print(G.T)

[[5 1 6 3]
 [2 7 0 8]
 [8 3 5 1]
 [4 9 2 7]]


### ידני:

In [ ]:
G = [5  2  8  4]
    [1  7  3  9]
    [6  0  5  2]
    [3  8  1  7]

In [ ]:
G.T =  [5
            